issuesOpened: >
  # Please do NOT use github for submitting issues!!!
  
  Instead **Please** submit bugs to the tracker on sr.ht
  [bug tracker](https://todo.sr.ht/~theorytoe/nii-nvim-bugs/)

  issues on github will be automatically replied to with this information
  I will probably not check issues submitted on github.

  You can also send an email to the mailing list:
  [lists.sr.ht/~theorytoe/nii-nvim-discuss](https://lists.sr.ht/~theorytoe/nii-nvim-discuss) if you have any questions.
